name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
jobs:

  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-experimental-features = nix-command flakes
      - run: nix flake check

  dogfood-check:
    name: dogfood-check
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-experimental-features = nix-command flakes
      - run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'nobody@example.com'
          nix run .#git-metrics -- pull
          nix run .#ci-script

  dogfood-master:
    name: dogfood-master
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - check
      - dogfood-check
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-experimental-features = nix-command flakes
      - run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'nobody@example.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          nix run .#git-metrics -- pull
          nix run .#ci-script
          nix run .#git-metrics -- push


